
title: SKILLED COOKIE
email: dan.jones@skilledcookie.com
description: >- # this means to ignore newlines until "baseurl:"
  A site containing blogs posts relating to all things software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.skilledcookie.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  danjones1986

permalink: pretty
favicon: /favicon.png
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
#theme_color: '#ee22dd'
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: skilledcookie

# Build settings
remote_theme: https://github.com/chrisrhymes/bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-131366467-1

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu
